# -*- coding: utf-8 -*-
"""creditcardfraud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PVtIL7wf63ixT5lyDEySvPARGRIcmUEW
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

!kaggle datasets download -d mlg-ulb/creditcardfraud

!unzip creditcardfraud.zip

data=pd.read_csv('/content/creditcard.csv')

data

from matplotlib import pyplot as plt
data['Time'].plot(kind='hist', bins=20, title='Time')
plt.gca().spines[['top', 'right',]].set_visible(False)

data.info()

data.describe()

data.isnull().sum()

data.columns

X = data.drop(columns=['Class']).values
y = data['Class'].values

from sklearn.preprocessing import MinMaxScaler

# Assuming df is your DataFrame and 'feature' is the column to normalize
scaler = MinMaxScaler()
X = scaler.fit_transform(X)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train, y_train)

y_pred= lr.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

y_pred= rf.predict(X_test)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))